# Generated by Django 5.2.4 on 2025-07-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do alimento')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço do alimento')),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade de kcalorias em 100g')),
                ('carbo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade de carboidratos em 100g')),
                ('proteina', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade de proteínas em 100g')),
                ('gorduratotais', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantida de gorduras totais em 100g')),
                ('gorduratrans', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade de gorduras trans em 100g')),
                ('gordurasaturada', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade de gorduras saturadas em 100g')),
                ('fibra', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade de fibras em 100g')),
                ('sodio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade de sódio em 100g')),
            ],
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Dia da semana')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do exercício')),
                ('descricao', models.CharField(max_length=100, verbose_name='Músculo alvo')),
                ('duracao', models.TimeField(verbose_name='Tempo de duração')),
                ('intensidade', models.CharField(max_length=100, verbose_name='Fácil, médio e difícil')),
                ('exemplo', models.CharField(max_length=100, verbose_name='Como executar')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nutricionista ou usuário comum')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da pessoa')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='Cpf da pessoa')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.CharField(max_length=100, verbose_name='Email da pessoa')),
                ('peso', models.CharField(max_length=100, verbose_name='Peso da pessoa')),
                ('altura', models.CharField(default='170', max_length=100, verbose_name='Altura da pessoa')),
                ('imc', models.CharField(max_length=100, verbose_name='IMC da pessoa')),
                ('tem_sentado', models.CharField(max_length=100, verbose_name='Tempo que a pessoa passa sentada ou parada')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Qual é sua meta')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDormir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField(verbose_name='Quantidade de tempo que a pessoa dormiu')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Feedback')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exercicio')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quanto de alimento você consumirá')),
                ('horario', models.TimeField(verbose_name='Horário que consumirá')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alimento')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diasemana')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niv_sedenta', models.CharField(max_length=100, verbose_name='Nível de sedentarismo')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
        ),
    ]
