# Generated by Django 5.2.4 on 2025-07-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='gorduratotais',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade de gorduras totais em 100g'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='kcal',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade de quilocalorias em 100g'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='duracao',
            field=models.DurationField(verbose_name='Tempo de duração'),
        ),
        migrations.AlterField(
            model_name='horariodormir',
            name='tempo',
            field=models.DurationField(verbose_name='Quantidade de tempo que a pessoa dormiu'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1.7, max_digits=4, verbose_name='Altura da pessoa (m)'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF da pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email da pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='IMC da pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso da pessoa (kg)'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tem_sentado',
            field=models.DurationField(verbose_name='Tempo que a pessoa passa sentada ou parada'),
        ),
    ]
