# Generated by Django 5.2.1 on 2025-05-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
