# Generated by Django 5.2.1 on 2025-05-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='turma',
        ),
        migrations.AddField(
            model_name='matricula',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
            preserve_default=False,
        ),
    ]
